name: LightningPlugin
version: 1.0
main: org.lightning.lightningPlugin.LightningPlugin
api-version: 1.20
author: Moshy0w0TM et Isax
description: LightningPlugin

commands:
  eclair:
    description: Envoie un eclair sur le joueur cible.
    usage: /eclair <joueur>
    permission: lightning.use
    permission-message: §cTu n'as pas la permission d'utiliser cette commande

permissions:
  lightning.use:
    description: Permet d'utiliser la commande /eclair
    default: op